FROM redis 
WORKDIR /redis
EXPOSE 6379
ENTRYPOINT redis-server
#ENV REDIS_HOST=localhost
#RUN apt update && apt install lsb-release curl gpg -y && curl -fsSL https://packages.redis.io/gpg |gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg && echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/redis.list && apt-get update && apt-get install redis -y
#CMD ["redis-server" ,"" ]
